# Generated by Django 3.2.7 on 2021-12-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211222_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
