# Generated by Django 3.2.9 on 2021-12-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forgot_password',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
