# Generated by Django 3.2.9 on 2021-12-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_forgot_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'available'), ('NOT AVAILABLE', 'not available')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
