# Generated by Django 3.2.9 on 2021-12-30 13:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211229_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=users.models.ProfileImages),
        ),
    ]
